templateDir: templates/server
additionalProperties:
  settings:
    - { "key": SQLALCHEMY_DATABASE_URI, "value": '"sqlite:///project.db"' }
files:
  __init__main.mustache:
    destinationFilename: openapi_server/__init__.py
    templateType: SupportingFiles
  config.mustache:
    destinationFilename: openapi_server/config.py
    templateType: SupportingFiles
