templateDir: templates/server
additionalProperties:
  settings:
    base:
      - { "key": Testing, "value": "False" }
    development:
      - { "key": SQLALCHEMY_DATABASE_URI, "value": '"sqlite:///project.db"' }
    testing:
      - { "key": SQLALCHEMY_DATABASE_URI, "value": '"sqlite:///test.db"' }
      - { "key": Testing, "value": "True" }
files:
  __init__main.mustache:
    destinationFilename: openapi_server/__init__.py
    templateType: SupportingFiles
  config.mustache:
    destinationFilename: openapi_server/config.py
    templateType: SupportingFiles
