openapi: 3.0.3
info:
  title: Sample User API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
  - url: http://localhost:8080
paths:
  /users:
    summary: Users
    get:
      operationId: get_users
      responses:
        "200":
          description: Get users
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /users/{name}:
    summary: User
    parameters:
      - name: name
        in: path
        description: user name
        required: true
        example: "sasaki"
        schema:
          $ref: "#/components/schemas/name"
    get:
      operationId: get_user
      responses:
        "200":
          description: Get user
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/User"
              examples:
                value:
                  $ref: "#/components/examples/UserGetExample"
        "400":
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/RequestError"
          description: Bad Request
    post:
      operationId: post_user
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/User"
            examples:
              UserPostExample:
                $ref: "#/components/examples/UserPostExample"
      responses:
        "201":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/User"
              examples:
                value:
                  $ref: "#/components/examples/UserPostExample"
        "400":
          description: Bad Request
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/RequestError"
components:
  schemas:
    User:
      type: object
      required:
        - name
        - grade
        - clubs
      properties:
        name:
          $ref: "#/components/schemas/name"
        grade:
          $ref: "#/components/schemas/grade"
        clubs:
          type: array
          items:
            $ref: "#/components/schemas/club"
    name:
      type: string
      format: name
    grade:
      type: integer
      format: int32
      minimum: 1
      maximum: 3
    club:
      type: string
      format: name
    RequestError:
      type: object
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string
        type:
          type: string
  examples:
    UserGetExample:
      value:
        name: "sasaki"
        grade: 1
        clubs:
          - Football
          - Baseball
    UserPostExample:
      value:
        name: "endo"
        grade: 1
        clubs:
          - Football
          - Baseball
