openapi: 3.0.3
info:
  title: Sample User API
  version: 1.0.0
servers:
- url: http://localhost:8080/api
- url: http://localhost:8080
paths:
  /users:
    get:
      operationId: get_users
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: Get users
      x-openapi-router-controller: openapi_server.controllers.default_controller
    summary: Users
  /users/{name}:
    get:
      operationId: get_user
      parameters:
      - description: user name
        example: sasaki
        explode: false
        in: path
        name: name
        required: true
        schema:
          $ref: '#/components/schemas/name'
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                value:
                  $ref: '#/components/examples/UserGetExample'
                  value: null
              schema:
                $ref: '#/components/schemas/User'
          description: Get user
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RequestError'
          description: Bad Request
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: post_user
      parameters:
      - description: user name
        example: sasaki
        explode: false
        in: path
        name: name
        required: true
        schema:
          $ref: '#/components/schemas/name'
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              UserPostExample:
                $ref: '#/components/examples/UserPostExample'
                value: null
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          content:
            application/json:
              examples:
                value:
                  $ref: '#/components/examples/UserPostExample'
                  value: null
              schema:
                $ref: '#/components/schemas/User'
          description: Success
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RequestError'
          description: Bad Request
      x-openapi-router-controller: openapi_server.controllers.default_controller
    summary: User
components:
  examples:
    UserGetExample:
      value:
        name: sasaki
        grade: 1
        clubs:
        - Football
        - Baseball
    UserPostExample:
      value:
        name: endo
        grade: 1
        clubs:
        - Football
        - Baseball
  schemas:
    User:
      example:
        grade: 1
        name: name
        clubs:
        - null
        - null
      properties:
        name:
          format: name
          title: name
          type: string
        grade:
          format: int32
          maximum: 3
          minimum: 1
          title: grade
          type: integer
        clubs:
          items:
            $ref: '#/components/schemas/club'
          title: clubs
          type: array
      required:
      - clubs
      - grade
      - name
      title: User
      type: object
    name:
      format: name
      title: name
      type: string
    grade:
      format: int32
      maximum: 3
      minimum: 1
      title: grade
      type: integer
    club:
      format: name
      title: club
      type: string
    RequestError:
      properties:
        detail:
          title: detail
          type: string
        status:
          title: status
          type: integer
        title:
          title: title
          type: string
        type:
          title: type
          type: string
      title: RequestError
      type: object
