"""Initial migration.

Revision ID: 21cc5515216c
Revises: 
Create Date: 2023-03-07 10:29:18.960739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cc5515216c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('club',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('club', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('name', 'club')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    op.drop_table('user')
    # ### end Alembic commands ###
